config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pagess#about'
  

resources :lists





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  def index
    @lists = List.all
  end

  def show
    @lists = List.find(params[:id])
  end

  def new
    @list = List.new
   end

  def create
    @list = List.new(lists_params) #path or params?
 
    if @list.save
      redirect_to lists_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
  
    if @list.update(lists_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    List.find(params[:id]).destroy
    redirect_to lists_path
  end
 
  private
 
    def lists_params
      params.require(:list).permit(:title, :author, :body)
    end

    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Lists', lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
  <% end %>

app/views/lists/index.html.erb
<h2> Welcome to the To Do Lists app! </h2>
<br />

<p><%= link_to 'New List', new_list_path %></p>
<% @lists.each do |list| %>
  <h2><%= list.title %></h2>
  <%= link_to 'View', list_path(list) %>
  <%= link_to 'Edit', edit_list_path(list) %>
    <%= link_to 'Delete', list, method: :delete %>
<% end %>

app/views/lists/new.html.erb
<h1>New List Item</h1>
<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br />
  <%= f.label :author %>
  <%= f.text_field :author %>
<br />
  <%= f.label :body %>
  <%= f.text_area :body %>
<br />
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<h4><%= @list.author %></h1>
<p><%= @list.body %></p>
<%= link_to 'Back', lists_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>